### Register a normal user
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "BMWDriver1",
  "password": "NoTurnSignal123",
  "role": "driver"
}

### Login as driver
POST http://localhost:8080/api/users/login
Authorization: Basic BMWDriver1:NoTurnSignal123

### Register a new fleet-manager
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "BigBoss1",
  "password": "BossPW123",
  "role": "fleet-manager"
}

### Login as fleet manager
POST http://localhost:8080/api/users/login
Authorization: Basic BigBoss1:BossPW123

### Retrieve all users (should only work for fleet managers)
GET http://localhost:8080/api/users
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>

### Register a new vehicle
POST http://localhost:8080/api/vehicles
Content-Type: application/json
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>

{
  "id": 1,
  "name": "3er BMW",
  "description": "Bavarian car",
  "latitude": 48.2082,
  "longitude": 16.3738,
  "state": "free",
  "currentDriver": null,
  "vehicleToken": "BMW123"
}

### Retrieve all vehicles
GET http://localhost:8080/api/vehicles
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>

### Retrieve a specific vehicle by ID
GET http://localhost:8080/api/vehicles/1
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>

### Update a vehicle
PUT http://localhost:8080/api/vehicles/1
Content-Type: application/json
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>

{
  "id": 1,
  "name": "3er BMW",
  "description": "Updated bavarian car",
  "latitude": 48.2082,
  "longitude": 16.3738,
  "state": "occupied",
  "currentDriver": "BMWDriver1",
  "vehicleToken": "BMW456"
}

### Delete a vehicle
DELETE http://localhost:8080/api/vehicles/1
Authorization: Bearer <INSERT_AUTH_TOKEN_HERE>
